# Generated by Django 3.2.25 on 2024-11-20 18:13

from django.db import migrations, models
import restframework_validation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.IntegerField(validators=[restframework_validation.models.validate_even])),
            ],
        ),
    ]
